CREATE schema IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS accounts (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  kind text NOT NULL DEFAULT 'default'
);

TRUNCATE TABLE accounts;
ALTER SEQUENCE accounts_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS users (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  account_id bigint NOT NULL REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  role text NOT NULL,
  status text NOT NULL
);

TRUNCATE TABLE users;
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS logins (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  at timestamp with time zone NOT NULL DEFAULT now(),
  user_id bigint NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

TRUNCATE TABLE logins;
ALTER SEQUENCE logins_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS groups (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  title text NOT NULL,
  starts timestamp with time zone NOT NULL,
  null_time timestamp with time zone,
  null_string text
);

TRUNCATE TABLE groups;
ALTER SEQUENCE groups_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS group_users (
  group_id bigint NOT NULL REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

TRUNCATE TABLE group_users;

CREATE VIEW accounts_view AS (
  SELECT
    0 AS id,
    '1970-01-01 00:00:00+00'::timestamp with time zone AS created_at,
    '1970-01-01 00:00:00+00'::timestamp with time zone AS updated_at,
    NULL::timestamp with time zone AS deleted_at,
    'view'::text AS kind
);

CREATE VIEW groups_view AS (
  SELECT
    0 AS id,
    '1970-01-01 00:00:00+00'::timestamp with time zone AS created_at,
    '1970-01-01 00:00:00+00'::timestamp with time zone AS updated_at,
    NULL::timestamp with time zone AS deleted_at,
    'view'::text AS title
);
