CREATE schema IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS accounts (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  kind text NOT NULL DEFAULT 'default'
);

TRUNCATE TABLE accounts;

CREATE TABLE IF NOT EXISTS users (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  account_id bigint NOT NULL REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  role text NOT NULL
);

TRUNCATE TABLE users;

CREATE TABLE IF NOT EXISTS logins (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  at timestamp with time zone NOT NULL DEFAULT now(),
  user_id bigint NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

TRUNCATE TABLE logins;

CREATE TABLE IF NOT EXISTS groups (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  title text NOT NULL
);

TRUNCATE TABLE groups;

CREATE TABLE IF NOT EXISTS group_users (
  group_id bigint NOT NULL REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

TRUNCATE TABLE group_users;
