name: Tag release
on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Pre-release"
    uses: ./.github/workflows/test.yml

  # https://github.com/marketplace/actions/github-tag-bump
  release:
    needs: pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.65.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.7.0
          DEFAULT_BUMP: patch
          